/*
# Initial Schema for Fraud Detection Platform

1. New Tables
   - `users` - User accounts with role-based access (Fraud Analyst, Manager, Admin)
   - `transactions` - Financial transactions for fraud scoring
   - `fraud_labels` - Ground truth labels for model training
   - `models` - ML model registry with versioning
   - `alerts` - Fraud alerts generated by the system
   - `audit_logs` - Compliance audit trail

2. Security
   - Enable RLS on all tables
   - Owner-scoped policies for authenticated users
   - Role-based access for sensitive operations

3. Indexes
   - Optimized for common query patterns (user lookup, transaction search, model retrieval)

4. Important Notes
   - user_id defaults to auth.uid() for automatic owner assignment
   - Timestamps use timestamptz for timezone awareness
   - JSONB used for flexible feature storage
*/

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Users table (extends auth.users for profile data)
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid() REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'analyst' CHECK (role IN ('analyst', 'manager', 'admin')),
    department TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    last_login TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Transactions table (core data for fraud detection)
CREATE TABLE IF NOT EXISTS transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES users(id) ON DELETE CASCADE,
    
    -- Transaction identifiers
    transaction_id TEXT UNIQUE NOT NULL,
    reference_number TEXT,
    
    -- Parties
    customer_id TEXT NOT NULL,
    customer_name TEXT,
    merchant_id TEXT NOT NULL,
    merchant_name TEXT,
    merchant_category TEXT,
    
    -- Transaction details
    amount DECIMAL(15, 2) NOT NULL,
    currency TEXT NOT NULL DEFAULT 'USD',
    transaction_type TEXT NOT NULL CHECK (transaction_type IN ('purchase', 'transfer', 'withdrawal', 'deposit', 'payment')),
    
    -- Location and device
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    country TEXT,
    city TEXT,
    ip_address TEXT,
    device_id TEXT,
    device_type TEXT,
    channel TEXT CHECK (channel IN ('web', 'mobile', 'pos', 'atm', 'api')),
    
    -- Timing
    transaction_timestamp TIMESTAMPTZ NOT NULL,
    local_hour INTEGER,
    day_of_week INTEGER,
    
    -- Pre-computed features (for fast scoring)
    features JSONB DEFAULT '{}'::JSONB,
    
    -- Scoring results
    risk_score DECIMAL(5, 2),
    risk_label TEXT CHECK (risk_label IN ('safe', 'suspicious', 'fraudulent')),
    model_id UUID,
    
    -- Status
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'reviewing', 'approved', 'rejected', 'flagged')),
    reviewed_by UUID REFERENCES users(id),
    reviewed_at TIMESTAMPTZ,
    review_notes TEXT,
    
    -- Metadata
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Fraud labels (ground truth for training)
CREATE TABLE IF NOT EXISTS fraud_labels (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    transaction_id TEXT NOT NULL REFERENCES transactions(transaction_id) ON DELETE CASCADE,
    is_fraud BOOLEAN NOT NULL,
    fraud_type TEXT CHECK (fraud_type IN ('card_fraud', 'identity_theft', 'account_takeover', 'money_laundering', 'other')),
    confidence DECIMAL(3, 2) DEFAULT 1.0,
    labeled_by UUID REFERENCES users(id),
    labeled_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    source TEXT CHECK (source IN ('manual', 'chargeback', 'investigation', 'confirmed')),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(transaction_id, source)
);

-- Model registry (track trained models)
CREATE TABLE IF NOT EXISTS models (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES users(id) ON DELETE CASCADE,
    
    -- Model identification
    name TEXT NOT NULL,
    version TEXT NOT NULL,
    model_type TEXT NOT NULL CHECK (model_type IN ('logistic_regression', 'random_forest', 'xgboost', 'lightgbm', 'neural_network', 'ensemble')),
    
    -- Training metadata
    training_config JSONB DEFAULT '{}'::JSONB,
    feature_columns TEXT[] DEFAULT '{}',
    
    -- Performance metrics
    metrics JSONB DEFAULT '{}'::JSONB,
    f1_score DECIMAL(5, 4),
    precision_score DECIMAL(5, 4),
    recall_score DECIMAL(5, 4),
    roc_auc DECIMAL(5, 4),
    pr_auc DECIMAL(5, 4),
    
    -- Training data info
    training_samples INTEGER,
    validation_samples INTEGER,
    fraud_rate DECIMAL(5, 4),
    training_duration_seconds INTEGER,
    
    -- File paths (stored in model storage)
    model_path TEXT,
    scaler_path TEXT,
    explainer_path TEXT,
    
    -- Status
    status TEXT NOT NULL DEFAULT 'training' CHECK (status IN ('training', 'validating', 'deployed', 'deprecated', 'failed')),
    is_active BOOLEAN DEFAULT false,
    deployed_at TIMESTAMPTZ,
    deployed_by UUID REFERENCES users(id),
    
    -- Timestamps
    trained_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
    UNIQUE(name, version)
);

-- Alerts table (generated fraud alerts)
CREATE TABLE IF NOT EXISTS alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES users(id) ON DELETE CASCADE,
    
    -- Alert identification
    alert_type TEXT NOT NULL CHECK (alert_type IN ('high_risk', 'anomaly', 'velocity', 'pattern', 'threshold')),
    severity TEXT NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    title TEXT NOT NULL,
    description TEXT,
    
    -- Related data
    transaction_ids TEXT[] DEFAULT '{}',
    model_id UUID REFERENCES models(id),
    rule_id TEXT,
    
    -- Risk information
    risk_score DECIMAL(5, 2),
    anomaly_score DECIMAL(5, 2),
    
    -- Status tracking
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'acknowledged', 'investigating', 'resolved', 'false_positive', 'escalated')),
    priority INTEGER DEFAULT 0,
    
    -- Assignment
    assigned_to UUID REFERENCES users(id),
    assigned_at TIMESTAMPTZ,
    
    -- Resolution
    resolved_by UUID REFERENCES users(id),
    resolved_at TIMESTAMPTZ,
    resolution_notes TEXT,
    resolution_type TEXT CHECK (resolution_type IN ('fraud_confirmed', 'fraud_prevented', 'false_positive', 'no_action')),
    
    -- Timestamps
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Audit logs (compliance trail)
CREATE TABLE IF NOT EXISTS audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    
    -- Action details
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT,
    
    -- Changes
    old_values JSONB,
    new_values JSONB,
    
    -- Request context
    ip_address TEXT,
    user_agent TEXT,
    request_id TEXT,
    
    -- Metadata
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_transaction_id ON transactions(transaction_id);
CREATE INDEX IF NOT EXISTS idx_transactions_customer_id ON transactions(customer_id);
CREATE INDEX IF NOT EXISTS idx_transactions_merchant_id ON transactions(merchant_id);
CREATE INDEX IF NOT EXISTS idx_transactions_timestamp ON transactions(transaction_timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_transactions_risk_score ON transactions(risk_score DESC);
CREATE INDEX IF NOT EXISTS idx_transactions_risk_label ON transactions(risk_label);
CREATE INDEX IF NOT EXISTS idx_transactions_status ON transactions(status);
CREATE INDEX IF NOT EXISTS idx_transactions_created_at ON transactions(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_fraud_labels_transaction_id ON fraud_labels(transaction_id);
CREATE INDEX IF NOT EXISTS idx_fraud_labels_labeled_at ON fraud_labels(labeled_at DESC);

CREATE INDEX IF NOT EXISTS idx_models_user_id ON models(user_id);
CREATE INDEX IF NOT EXISTS idx_models_status ON models(status);
CREATE INDEX IF NOT EXISTS idx_models_is_active ON models(is_active);
CREATE INDEX IF NOT EXISTS idx_models_type ON models(model_type);
CREATE INDEX IF NOT EXISTS idx_models_trained_at ON models(trained_at DESC);

CREATE INDEX IF NOT EXISTS idx_alerts_user_id ON alerts(user_id);
CREATE INDEX IF NOT EXISTS idx_alerts_status ON alerts(status);
CREATE INDEX IF NOT EXISTS idx_alerts_severity ON alerts(severity);
CREATE INDEX IF NOT EXISTS idx_alerts_created_at ON alerts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_assigned_to ON alerts(assigned_to);

CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at DESC);

-- Enable Row Level Security
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE fraud_labels ENABLE ROW LEVEL SECURITY;
ALTER TABLE models ENABLE ROW LEVEL SECURITY;
ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- RLS Policies for users
DROP POLICY IF EXISTS "select_own_users" ON users;
CREATE POLICY "select_own_users" ON users FOR SELECT
    TO authenticated USING (auth.uid() = id OR EXISTS (
        SELECT 1 FROM users WHERE id = auth.uid() AND role IN ('manager', 'admin')
    ));

DROP POLICY IF EXISTS "insert_own_users" ON users;
CREATE POLICY "insert_own_users" ON users FOR INSERT
    TO authenticated WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "update_own_users" ON users;
CREATE POLICY "update_own_users" ON users FOR UPDATE
    TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- RLS Policies for transactions
DROP POLICY IF EXISTS "select_own_transactions" ON transactions;
CREATE POLICY "select_own_transactions" ON transactions FOR SELECT
    TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_transactions" ON transactions;
CREATE POLICY "insert_own_transactions" ON transactions FOR INSERT
    TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_transactions" ON transactions;
CREATE POLICY "update_own_transactions" ON transactions FOR UPDATE
    TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_transactions" ON transactions;
CREATE POLICY "delete_own_transactions" ON transactions FOR DELETE
    TO authenticated USING (auth.uid() = user_id);

-- RLS Policies for fraud_labels
DROP POLICY IF EXISTS "select_own_fraud_labels" ON fraud_labels;
CREATE POLICY "select_own_fraud_labels" ON fraud_labels FOR SELECT
    TO authenticated USING (EXISTS (
        SELECT 1 FROM transactions WHERE transactions.transaction_id = fraud_labels.transaction_id AND transactions.user_id = auth.uid()
    ));

DROP POLICY IF EXISTS "insert_own_fraud_labels" ON fraud_labels;
CREATE POLICY "insert_own_fraud_labels" ON fraud_labels FOR INSERT
    TO authenticated WITH CHECK (EXISTS (
        SELECT 1 FROM transactions WHERE transactions.transaction_id = fraud_labels.transaction_id AND transactions.user_id = auth.uid()
    ));

-- RLS Policies for models
DROP POLICY IF EXISTS "select_own_models" ON models;
CREATE POLICY "select_own_models" ON models FOR SELECT
    TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_models" ON models;
CREATE POLICY "insert_own_models" ON models FOR INSERT
    TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_models" ON models;
CREATE POLICY "update_own_models" ON models FOR UPDATE
    TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_models" ON models;
CREATE POLICY "delete_own_models" ON models FOR DELETE
    TO authenticated USING (auth.uid() = user_id);

-- RLS Policies for alerts
DROP POLICY IF EXISTS "select_own_alerts" ON alerts;
CREATE POLICY "select_own_alerts" ON alerts FOR SELECT
    TO authenticated USING (auth.uid() = user_id OR auth.uid() = assigned_to);

DROP POLICY IF EXISTS "insert_own_alerts" ON alerts;
CREATE POLICY "insert_own_alerts" ON alerts FOR INSERT
    TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_alerts" ON alerts;
CREATE POLICY "update_own_alerts" ON alerts FOR UPDATE
    TO authenticated USING (auth.uid() = user_id OR auth.uid() = assigned_to) 
    WITH CHECK (auth.uid() = user_id OR auth.uid() = assigned_to);

-- RLS Policies for audit_logs (read-only for admins)
DROP POLICY IF EXISTS "select_audit_logs_admin" ON audit_logs;
CREATE POLICY "select_audit_logs_admin" ON audit_logs FOR SELECT
    TO authenticated USING (EXISTS (
        SELECT 1 FROM users WHERE id = auth.uid() AND role = 'admin'
    ));

DROP POLICY IF EXISTS "insert_audit_logs" ON audit_logs;
CREATE POLICY "insert_audit_logs" ON audit_logs FOR INSERT
    TO authenticated WITH CHECK (true);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply update triggers
DROP TRIGGER IF EXISTS update_users_updated_at ON users;
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_transactions_updated_at ON transactions;
CREATE TRIGGER update_transactions_updated_at BEFORE UPDATE ON transactions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_models_updated_at ON models;
CREATE TRIGGER update_models_updated_at BEFORE UPDATE ON models
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_alerts_updated_at ON alerts;
CREATE TRIGGER update_alerts_updated_at BEFORE UPDATE ON alerts
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
